### ISSUE TITLE
Bettercap 2 fix 

### ISSUE THREAD

**Issue by ChillVibesMushroom** [adde88/openwrt-useful-tols#21]
I noticed when running bettercap 2 I'm targeting the WiFi enabled router from my pineapple and sometimes I can capture network traffic other times it doesn't pull through.

Why can't I capture on br-lan interface If you need more information let me know

**Comment by adde88** [comment]
br-lan is NOT your wireless interface.
That's just a bridge between interfaces.
You should set wlan1, or wlan2, in monitor mode.

**Comment by ChillVibesMushroom** [comment]
> br-lan is NOT your wireless interface. That's just a bridge between interfaces. You should set wlan1, or wlan2, in monitor mode.

Which one would I put it in monitor mode and why if I'm doing and mitma

**Comment by adde88** [comment]
I'm not sure i'm getting ur question. I said that wlan1 or wlan2 can be used in monitor mode. That should answer your question.
If you really are asking why to put it in monitor mode, then i really suggest you start learning something easier! 
Or read up on the attack vectors you are using, before attempting them. Because if used incorrectly, they can land you some serious jail-time!

**Comment by ChillVibesMushroom** [comment]
I figured it out you mean to target wlan1 or wlan1 because that’s where the device are connected duuuur
