### ISSUE TITLE
Hostapd-mana

### ISSUE THREAD

**Issue by hillero** [adde88/openwrt-useful-tols#9]
Hi,

Im having an issue with running hostapd-mana on a wifi-pineapple mark VII.

I keep getting the error below (have tried all the interfaces).

_nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan1 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan1: interface state UNINITIALIZED->DISABLED
wlan1: AP-DISABLED
hostapd_free_hapd_data: Interface wlan1 wasn't started_

the config file looks like this:

_interface=wlan1
ssid=test
channel=6
hw_mode=g
wpa=3
wpa_key_mgmt=WPA-EAP
wpa_pairwise=TKIP CCMP
auth_algs=3
ieee8021x=1
eapol_key_index_workaround=0
eap_server=1
eap_user_file=hostapd.eap_user
ca_cert=ca.pem
server_cert=server.pem
private_key=server.key
private_key_passwd=
dh_file=dhparam.pem
mana_wpe=1
mana_eapsuccess=1_

Do you know what the problem could be?

**Comment by adde88** [comment]
It seems this problem was caused by an error during compilation, which caused 802.11n (among other compile time options) to not work properly.
I've looked into the problem, and fixed it.

That being said, there's another "problem" to handle here as well.
There's only one of the MK7's total of three wireless adapters that supports "AP-mode". Which is wlan0.
Since the internal hostapd is already running on wlan0, you will need to stop it first if you want to run it there.
For example like this works: ```killall -9 hostapd;hostapd-mana /etc/hostapd-mana/hostapd-mana.conf```

**Comment by hillero** [comment]
Thank you for the fast response Andreas. Got it to work now, but i for some reason needed to run both airmon-ng check kill wlan0 and killall -9 hostapd to get it to run... 

Cheers!

**Comment by adde88** [comment]
> Thank you for the fast response Andreas. Got it to work now, but i for some reason needed to run both airmon-ng check kill wlan0 and killall -9 hostapd to get it to run...
> 
> Cheers!

No prob'! Glad i was able to help. 👍 
Yeah, i forgot about airmon-ng. That would most likely also work.
I had to use a one-liner to make it launch, as hostapd gets re-launched again almost instantly on OpenWRT.

Thanks for reporting the error btw. Have a good day :)
